### ISSUE TITLE
Is highway_env used?

### ISSUE THREAD

**Issue by aravindvenu7** [laonahongchen/Bilevel-Optimization-in-Coordination-Game#1]
run_trainer_highway_bilevel.py seems to be using OpenAI gym Merge instead of the highway_env

**Comment by logWin322** [comment]
We have already register the highway environemnt in OpenAI gym. To create the environment, run:  **env = gym.make("merge-v0")** . The implementaion of this environemnt is in the highway_env directory.

**Comment by aravindvenu7** [comment]
In merge_env.py, rewards are set to 0, and the code for calculating rewards is commented out.  Could you please tell me which parts I should uncomment to get the same game as used in your paper?

**Comment by logWin322** [comment]
You don't need to modify anything. The detailed design of our reward function can be found in highway_env/envs/common/abstract.py, line 204-247.

**Comment by aravindvenu7** [comment]
Okay. Thank you. One last doubt. The value that is plotted in Fig. 7 of your paper, does it use env.episode_merge_record or env.episode_target_merge_record. Would like to know the difference between both of these variables.

**Comment by logWin322** [comment]
env.episode_merge_record: successful merge 
env.episode_target_merge_record: successful merge and leader go first (in our settings, we want to make leaders go first)

**Comment by aravindvenu7** [comment]
Thank you very much!
